export const DISPOSABLE_DOMAINS = new Set([
  "mailinator.com",
  "tempmail.com",
  "guerrillamail.com",
  "temp-mail.org",
  "dispostable.com",
  "yopmail.com",
  "maildrop.cc",
  "10minutemail.com",
  "throwawaymail.com",
  "sharklasers.com",
  "getairmail.com",
  "mailnesia.com",
  "fakeinbox.com",
  "trashmail.com",
  "tempmailaddress.com",
  "tempr.email",
  "tempinbox.com",
  "getnada.com",
  "emailondeck.com",
  "anonbox.net",
  "mailcatch.com",
  "temp-mail.ru",
  "spamgourmet.com",
  "mytemp.email",
  "mailforspam.com",
  "mohmal.com",
  "harakirimail.com",
  "inboxalias.com",
  "dropmail.me",
  "mintemail.com",
  "anonymbox.com",
  "incognitomail.com",
  "tempinbox.net",
  "emailtemporario.com.br",
  "jetable.org",
  "mailexpire.com",
  "tempomail.fr",
  "fakemail.net",
  "emailfake.com",
  "throwam.com",
  "burnermail.io",
  "temporary-mail.net",
  "spambox.us",
  "grr.la",
  "guerrillamail.net",
  "guerrillamail.org",
  "guerrillamail.biz",
  "spam4.me",
  "trashmail.net",
  "33mail.com",
]);

export const FREE_EMAIL_PROVIDERS = new Set([
  "gmail.com",
  "yahoo.com",
  "hotmail.com",
  "outlook.com",
  "aol.com",
  "icloud.com",
  "protonmail.com",
  "mail.com",
  "zoho.com",
  "yandex.com",
  "gmx.com",
  "live.com",
  "inbox.com",
  "tutanota.com",
  "fastmail.com",
  "msn.com",
  "me.com",
  "comcast.net",
  "verizon.net",
  "att.net",
  "rocketmail.com",
  "cox.net",
  "sbcglobal.net",
  "rediffmail.com",
  "bellsouth.net",
  "charter.net",
  "earthlink.net",
  "mac.com",
  "aim.com",
  "mail.ru",
  "yeah.net",
  "qq.com",
  "163.com",
  "126.com",
  "foxmail.com",
  "web.de",
  "gmx.de",
  "gmx.net",
  "t-online.de",
  "libero.it",
  "rambler.ru",
  "orange.fr",
  "free.fr",
  "laposte.net",
  "wanadoo.fr",
  "mail.yahoo.co.jp",
  "ezweb.ne.jp",
  "docomo.ne.jp",
  "naver.com",
  "hanmail.net",
]);

export const ROLE_BASED_PREFIXES = new Set([
  "admin",
  "info",
  "support",
  "sales",
  "contact",
  "help",
  "service",
  "billing",
  "marketing",
  "webmaster",
  "postmaster",
  "hostmaster",
  "abuse",
  "security",
  "noreply",
  "no-reply",
  "mail",
  "office",
  "hr",
  "jobs",
  "careers",
  "team",
  "accounts",
  "customerservice",
  "inquiry",
  "feedback",
  "hello",
  "webinfo",
  "general",
  "orders",
  "reservations",
  "booking",
  "newsletter",
  "press",
  "media",
  "legal",
  "complaints",
  "it",
  "tech",
  "technical",
  "developer",
  "partners",
  "affiliates",
  "events",
  "community",
  "welcome",
  "privacy",
  "notifications",
  "alerts",
  "updates",
]);

export const DOMAIN_TYPOS: Record<string, string> = {
  "gmial.com": "gmail.com",
  "gmal.com": "gmail.com",
  "gamil.com": "gmail.com",
  "gnail.com": "gmail.com",
  "gmali.com": "gmail.com",
  "gmil.com": "gmail.com",
  "gmaill.com": "gmail.com",
  "gmai.com": "gmail.com",
  "gmail.co": "gmail.com",
  "gmail.cm": "gmail.com",
  "gmail.comm": "gmail.com",
  "gmsil.com": "gmail.com",
  "gmailc.om": "gmail.com",
  "hotmial.com": "hotmail.com",
  "hotmal.com": "hotmail.com",
  "hotmai.com": "hotmail.com",
  "hotamail.com": "hotmail.com",
  "hotmil.com": "hotmail.com",
  "hotmail.co": "hotmail.com",
  "htmail.com": "hotmail.com",
  "hotmali.com": "hotmail.com",
  "hotmial.co": "hotmail.com",
  "hotmail.cm": "hotmail.com",
  "yaho.com": "yahoo.com",
  "yahooo.com": "yahoo.com",
  yahocom: "yahoo.com",
  "yahoo.co": "yahoo.com",
  "yhaoo.com": "yahoo.com",
  "yaoo.com": "yahoo.com",
  "yaaho.com": "yahoo.com",
  "yahoo.cm": "yahoo.com",
  "ymail.com": "yahoo.com",
  "outloo.com": "outlook.com",
  "outlok.com": "outlook.com",
  "outlook.co": "outlook.com",
  "outlook.cm": "outlook.com",
  "outlookc.om": "outlook.com",
  "outlokk.com": "outlook.com",
  "outllook.com": "outlook.com",
  "outlok.co": "outlook.com",
  "oulook.com": "outlook.com",
  "aol.co": "aol.com",
  "aol.cm": "aol.com",
  "aol.comm": "aol.com",
  "aol.con": "aol.com",
  "alo.com": "aol.com",
  "aoll.com": "aol.com",
  "ao.com": "aol.com",
  "icoud.com": "icloud.com",
  "iclod.com": "icloud.com",
  "iclud.com": "icloud.com",
  "icloud.co": "icloud.com",
  "icloude.com": "icloud.com",
  "comacast.net": "comcast.net",
  "concast.net": "comcast.net",
  "cmcast.net": "comcast.net",
  "comcastt.net": "comcast.net",
  "comcat.net": "comcast.net",
};
